p8105\_hw1\_dz2399
================
DZ
September 29, 2018

Problem 1
---------

### Read in the data according to instuctions

``` r
df_nyc <- read_csv(file='./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv') %>%
  janitor::clean_names() %>%
  select(line, starts_with('station'),starts_with('route'),entry, vending,ada,entrance_type) %>% 
  select(-station_location) %>% 
  mutate(entry = recode (entry, 'YES' = T, 'NO'=F))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
dim(df_nyc)
```

    ## [1] 1868   19

The dataset contains the following variables: line, station\_name, station longitute and latitude, the route that the train serves, entry and entry types, vending, and ada. The data cleaning process is that: firstly, read in the data from the directory and conduct a column-name-cleaning with the function clean\_names; then, select the desired variables; lastly, recode the entry variable with yes equals to T and no to F. The dimension of the resulting dataset is 1868, 19. This is not a tidy data, because the route variables are spreadout to multiple columns rather than a single column.

#### How many distinct stations are there?

``` r
dim(distinct(df_nyc, station_name))[1]
```

    ## [1] 356

There are 356 distinct stations in the dataset.

#### How many stations are ADA compliant?

``` r
df_nyc %>% 
  filter(ada==T) %>% 
  distinct(station_name) %>% 
  dim()
```

    ## [1] 73  1

There are 73 stations that are ADA compliant in the dataset.

#### What proportion of station entrances / exits without vending allow entrance?

``` r
dim(df_nyc %>% filter(vending=='NO'))[1]/dim(df_nyc)[1]
```

    ## [1] 0.09796574

Among all entrancss/ exits in the dataset, 9.7% of the entrance/exit do not have vending machines.

#### How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?

``` r
df_nyc %>% 
  gather(key=route_number, value=route_name,route1:route11) %>% 
  filter(route_name=='A') %>% 
  distinct(station_name) %>% 
  dim()
```

    ## [1] 56  1

``` r
df_nyc %>% 
  gather(key=route_number, value=route_name,route1:route11) %>% 
  filter(route_name=='A',ada==T) %>% 
  distinct(station_name) %>% 
  dim()
```

    ## [1] 16  1

Therefore, 56 stations serves the A train in the dataset, and of those 56 stations, 16 stations are APA compliant.

Problem 2
---------

#### Read and clean the Mr. Trash Wheel sheet:

-   specify the sheet in the Excel file and to omit columns containing notes (using the range argument and cell\_cols() function)
-   use reasonable variable names
-   omit rows that do not include dumpster-specific data
-   rounds the number of sports balls to the nearest integer and converts the result to an integer variable (using as.integer)

``` r
df_tw <- readxl::read_excel('./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx',range='A2:N258') %>% 
  janitor::clean_names() %>% 
  filter(!dumpster=='NA') %>% 
  mutate(sports_balls = as.integer(round(sports_balls,0)))
```

#### Read and clean precipitation data for 2016 and 2017.

For each, omit rows without precipitation data and add a variable year. Next, combine datasets and convert month to a character variable (the variable month.name is built into R and should be useful).

``` r
precip_2017 <- readxl::read_excel('./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx',
                                 sheet=3, range = 'A2:B15') %>% 
  mutate(year= rep(2017,13)) %>% 
  filter(!Total=='NA',!Month=='NA')

precip_2016 <- readxl::read_excel('./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx',
                                 sheet=4, range = 'A2:B15') %>% 
  mutate(year= rep(2016,13)) %>% 
  filter(!Total=='NA',!Month=='NA')

precip_full <- rbind(precip_2016,precip_2017) %>% 
  mutate(Month = as.factor(Month))
levels(precip_full$Month) <- month.name
precip_full
```

    ## # A tibble: 20 x 3
    ##    Month     Total  year
    ##    <fct>     <dbl> <dbl>
    ##  1 January    3.23  2016
    ##  2 February   5.32  2016
    ##  3 March      2.24  2016
    ##  4 April      1.78  2016
    ##  5 May        5.19  2016
    ##  6 June       3.2   2016
    ##  7 July       6.09  2016
    ##  8 August     3.96  2016
    ##  9 September  4.53  2016
    ## 10 October    0.62  2016
    ## 11 November   1.47  2016
    ## 12 December   2.32  2016
    ## 13 January    2.34  2017
    ## 14 February   1.46  2017
    ## 15 March      3.57  2017
    ## 16 April      3.99  2017
    ## 17 May        5.64  2017
    ## 18 June       1.4   2017
    ## 19 July       7.09  2017
    ## 20 August     4.44  2017

The resulting 2017 precipitation data has the dimension of 8, 3, and the resulting 2016 precipitation data has the dimension of 12, 3 Be sure to note the number of observations in both resulting datasets, and give examples of key variables. For available data, what was the total precipitation in 2017? What was the median number of sports balls in a dumpster in 2016?

The p
